@api = http://localhost:5073

### add product
Post {{api}}/product
Content-Type: application/json

{
"name": "Pasek do garnituru",
"description": "czysta skóra",
"price": 11.99,
"categoryId": "a9df4678-1881-4728-82b3-141186c668b3"
} 

### update product
PUT {{api}}/product/9E49DC22-BE85-4240-8448-3CF891DD82F9
Content-Type: application/json

{
"name": "Pasek do spodni",
"description": "czysta skóra (PROMOCJA)",
"price": 7.99,
"categoryId": "E9E846D8-D80C-4BE0-9209-FF4E257B7618"
}

