@api = http://localhost:5073

### add product
Post {{api}}/product
Content-Type: application/json

{
"name": "Pasek do spodni",
"description": "czysta skóra",
"price": 11.99,
"categoryId": ""
} 

### add category
Post {{api}}/category
Content-Type: application/json

{
"name": "Ubrania",
} 
